print("-----------------------------------------------------")
print("|                                                    |")
print("|                                                    |")
print("|                Safaricom Limited                   |")
print("|               Simple Transparent Honest            |")
print("|                est 1994                            |")
print("|                                                    |")
print("|                                                    |")
print("|                                                    |")
print("|                                                    |")
print("|                                                    |")
print("|                                                    |")
print("|                                                    |")
print("|                                                    |")
print("-----------------------------------------------------|")